// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIdQcvXg6DpUqg94j4oibwEawOndG4JUM',
    appId: '1:277371488496:web:ea6aada93c53e52d33da35',
    messagingSenderId: '277371488496',
    projectId: 'acceleratorx-f667f',
    authDomain: 'acceleratorx-f667f.firebaseapp.com',
    storageBucket: 'acceleratorx-f667f.firebasestorage.app',
    measurementId: 'G-1RKX80MVZX',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIdQcvXg6DpUqg94j4oibwEawOndG4JUM',
    appId: '1:277371488496:web:6311dae5fa90b48a33da35',
    messagingSenderId: '277371488496',
    projectId: 'acceleratorx-f667f',
    authDomain: 'acceleratorx-f667f.firebaseapp.com',
    storageBucket: 'acceleratorx-f667f.firebasestorage.app',
    measurementId: 'G-GBRKZ7BTSL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdxN80RLkZbPZs_PF9GmZAlcKyMio3N_E',
    appId: '1:277371488496:ios:2dd5dc22fbb9e56b33da35',
    messagingSenderId: '277371488496',
    projectId: 'acceleratorx-f667f',
    storageBucket: 'acceleratorx-f667f.firebasestorage.app',
    iosBundleId: 'com.example.taskSharingApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdxN80RLkZbPZs_PF9GmZAlcKyMio3N_E',
    appId: '1:277371488496:ios:2dd5dc22fbb9e56b33da35',
    messagingSenderId: '277371488496',
    projectId: 'acceleratorx-f667f',
    storageBucket: 'acceleratorx-f667f.firebasestorage.app',
    iosBundleId: 'com.example.taskSharingApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBiyIpfyW-vAwUroxGrbVt-zdn0vkIskg',
    appId: '1:277371488496:android:bc7a3a28770125ce33da35',
    messagingSenderId: '277371488496',
    projectId: 'acceleratorx-f667f',
    storageBucket: 'acceleratorx-f667f.firebasestorage.app',
  );

}